spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-consumes-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645357566B5970
      expiration: 360000
